change import logic

diff --git a/import b/import
--- a/import
+++ b/import
@@ -1,4 +1,4 @@
-#! /bin/bash
+#!/bin/bash
 
 #-----------------------------------------------------#
 # This file is intended to be included within scripts #
@@ -9,8 +9,9 @@
 # Init #
 #------#
 
-IMPORT_SRC="import"
+IMPORT_SRC=
 __import_dbg_enabled=0
+IMPORT_DIR="$( cd "$( dirname "${0}" )" && pwd )"
 
 
 #---------#
@@ -20,25 +21,10 @@ __import_dbg_enabled=0
 __import_dbg_print () {
   msg="${1}"
   if [ "${__import_dbg_enabled}" = 1 ]; then
-    printf "debug: ${msg}\n" >&1
+    printf "debug: \n" "${msg}" >&1
   fi
 }
 __import_dbg_print "entering import"
-
-
-#-----------------------#
-# External Dependencies #
-#-----------------------#
-
-#-------------------------------
-#
-# This file depends on an environment variable LIBRARY_FXNS to be set to a valid directory where all default
-#   library imports will take place.  This instantiation should be located in .bashrc or .bash_profile,
-#   and should have already been taken care of during installation.  However, if for some reason this
-#   variable wasn't set, or is erased when 'import' is called, this file assumes its default value
-#   of ${HOME}/library-fxns/
-#
-#-------------------------------
 
 
 #-----#
@@ -47,23 +33,22 @@ __import_dbg_print "entering import"
 
 #-------------------------------
 #
+# Public Constant: IMPORT_DIR
+#
+# Desciption: This holds the absolute directory name where imports are searched
+#
+#-------------------------------
+#
 # Function: import <file>
 #
 # Arguments:
 #   <file> - The name of the file to import.  Currently the file is assumed to exist in
-#              ${HOME}/library-fxns/*
+#     ${HOME}/library-fxns/*
 #
 # Description: This function allows scripts to easily import each other by assuming certain
-#                naming conventions.
+#   naming conventions.
 #
 #-------------------------------
-
-
-#------------------#
-# Script Variables #
-#------------------#
-
-import_default_home="${HOME}/library-fxns"
 
 
 #-----------#
@@ -73,34 +58,26 @@ import_default_home="${HOME}/library-fxns"
 import () {
   local file="${1}"
 
-  if [ -z "${LIBRARY_FXNS+x}" ]; then
-    local LIBRARY_FXNS="${import_default_home}"
-    elif [ ! -d "${LIBRARY_FXNS}" ]; then
-    printf "'LIBRARY_FXNS' doesn't point to a valid directory\n" >&2
+  if [ ! -f "${IMPORT_DIR}/${file}.sh" ]; then
+    local msg="Import '${1}' failed - file '${IMPORT_DIR}/${file}.sh' was not found\n"
+
+    # The below code is copied from log-fatal.  Unable to import it because that
+    #   would create a circular reference
+    printf "%bError:%b\n\n" "${RED}" "${RESET} ${msg}" >&2
+    printf "Please report a github issue so I can help you and others:\n" >&2
+    printf "https://github.com/olsonpm/lilyvm/issues/new\n" >&2
     exit 1
   fi
 
-  if [ ! -f "${LIBRARY_FXNS}/${file}" ] && [ ! -f "${file}" ]; then
-    printf "imported file (${1}) doesn't exist\n" >&2
-    exit 1
-  fi
-
-  local e="$((${#file}-5))"
-  if [ "${file:${e}:5}" = ".blib" ]; then
-    file="${file:0:${e}}"
-  fi
-
-  local src=$(basename "${file}" | tr '[:lower:]' '[:upper:]')"_SRC"
-  if [ -z "${!src+x}" ]; then
-    if [ -f "${LIBRARY_FXNS}/${file}" ]; then
-      __import_dbg_print "importing ${LIBRARY_FXNS}/${file}"
-      source "${LIBRARY_FXNS}/${file}"
-    else # [ -f "${file}" ]; then
-      __import_dbg_print "importing ${file}"
-      source "${file}"
+  local src=$(basename "${file}" | tr '[:lower:]' '[:upper:]' | tr '-' '_' )"_SRC"
+  eval src=\$$src
+  if [ "${src}" != 1 ]; then
+    if [ -f "${IMPORT_DIR}/${file}.sh" ]; then
+      __import_dbg_print "importing ${IMPORT_DIR}/${file}.sh"
+      . "${IMPORT_DIR}/${file}.sh"
     fi
   else
-    __import_dbg_print "${LIBRARY_FXNS}/${file} has already been imported"
+    __import_dbg_print "${IMPORT_DIR}/${file} has already been imported"
   fi
 }
 
